version: '3'

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    depends_on:
      - home-api
      - security-api
      - weather-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
    ports:
      - 80:80

  home-api:
    image: containous/whoami
    container_name: home-api
    ports:
      - 8080:80 

  security-api:
    image: containous/whoami
    container_name: security-api
    ports:
      - 8090:80

  weather-api:
    image: containous/whoami
    container_name: weather-api
    ports:
      - 8091:80
